package advise

import (
	"fmt"
	"net/url"
	"strings"

	"github.com/Allan-Nava/robotsmith/internal/matcher"
)

// AutoBlockShare is the share above which an unknown crawler is written ACTIVE instead of
// commented out. Below this threshold the burden of proof is on whoever blocks (the cost is small,
// the risk of cutting off an unknown channel is not); above it, the cost is such that the burden
// flips and the line must be written — with the number next to it, so the decision is checkable.
const AutoBlockShare = 3.0

// Render produces the content of the advised robots.txt.
//
// `existing` is the current file (it may be empty): its rules for `User-agent: *` are carried over
// UNCHANGED, because they were written for that site and this algorithm does not know why.
// `host` decides whether the `Sitemap:` line is kept: pointing at another domain's sitemap is
// useless and, in Search Console, a wrong signal.
func Render(a *Advice, existing, host string) string {
	var b strings.Builder
	cur := matcher.Parse(existing)

	b.WriteString("# robots.txt generated by robotsmith (github.com/Allan-Nava/robotsmith)\n")
	if a.Total > 0 {
		b.WriteString(fmt.Sprintf("# Based on %s observed requests. The advised blocks touch %.1f%% of them.\n",
			thousands(a.Total), a.Saving))
	}
	b.WriteString("#\n# ⚠️ robots.txt is a REQUEST, not a control: whoever disguises itself as a browser ignores it.\n")
	b.WriteString("#    For those you need a request cap or a WAF.\n")

	// 1) Explicit allowlist: not technically necessary (whatever is not forbidden is allowed), but
	//    it makes it obvious to the reader that those crawlers are wanted — and it prevents the
	//    "block everything except two" that ends in deindexing.
	if hasPolicy(a, Allow) {
		b.WriteString("\n# ── Allowed on purpose: they bring visits ───────────────────────────\n")
		for _, d := range a.Decisions {
			if d.Policy != Allow {
				continue
			}
			b.WriteString(fmt.Sprintf("# %s — %s\n", d.Family, d.Why))
			b.WriteString("User-agent: " + d.Name + "\n")
			b.WriteString("Allow: /\n")
		}
	}

	// 2) Blocks, in order of convenience (descending volume).
	if hasPolicy(a, Block) || hasPolicy(a, Candidate) {
		b.WriteString("\n# ── Blocked: they take content without bringing visits ──────────────\n")
		for _, d := range a.Decisions {
			if d.Policy != Block && d.Policy != Candidate {
				continue
			}
			active := d.Policy == Block || d.Share >= AutoBlockShare
			pref := ""
			if !active {
				pref = "# "
				b.WriteString(fmt.Sprintf("# ⏳ TO BE CONFIRMED (%.1f%% of the requests): uncomment it if it brings no visits.\n", d.Share))
			} else if d.Policy == Candidate {
				b.WriteString(fmt.Sprintf("# ⚠️ Unrecognised but heavy crawler: %.1f%% of the requests (%s).\n",
					d.Share, thousands(d.Requests)))
			}
			b.WriteString(pref + "User-agent: " + d.Name + "\n")
			b.WriteString(pref + "Disallow: /\n")
		}
	}

	// 3) The `*` group: existing rules carried over as they are.
	b.WriteString("\n# ── General rules ───────────────────────────────────────────────────\n")
	star := starGroup(cur)
	if star == nil {
		b.WriteString("User-agent: *\n")
		b.WriteString("# No pre-existing rule found: add the private paths here\n")
		b.WriteString("# (admin area, APIs, login flows) — this tool does not know them.\n")
		b.WriteString("Disallow:\n")
	} else {
		b.WriteString("User-agent: *\n")
		for _, r := range star.Rules {
			verb := "Disallow: "
			if r.Allow {
				verb = "Allow: "
			}
			b.WriteString(verb + r.Pattern + "\n")
		}
		if len(cur.Orphans) > 0 {
			b.WriteString("# ⚠️ The lines below were ORPHANED in the previous file (after a blank line\n")
			b.WriteString("#    inside the group): a strict parser ignored them. Recovered here.\n")
			for _, r := range cur.Orphans {
				verb := "Disallow: "
				if r.Allow {
					verb = "Allow: "
				}
				b.WriteString(verb + r.Pattern + "\n")
			}
		}
	}

	// 4) Sitemap: only if it is on the same host.
	for _, sm := range cur.Sitemaps {
		if sameHost(sm, host) {
			b.WriteString("\nSitemap: " + sm + "\n")
		} else {
			b.WriteString("\n# ⚠️ Sitemap dropped: it points to another host (" + sm + ").\n")
			b.WriteString("#    A cross-domain sitemap is not considered.\n")
		}
	}
	return b.String()
}

func hasPolicy(a *Advice, p Policy) bool {
	for _, d := range a.Decisions {
		if d.Policy == p {
			return true
		}
	}
	return false
}

func starGroup(r *matcher.RobotsTxt) *matcher.Group {
	for i := range r.Groups {
		for _, ag := range r.Groups[i].Agents {
			if ag == "*" {
				return &r.Groups[i]
			}
		}
	}
	return nil
}

func sameHost(sitemap, host string) bool {
	if host == "" {
		return true
	}
	u, err := url.Parse(sitemap)
	if err != nil {
		return false
	}
	a := strings.TrimPrefix(strings.ToLower(u.Hostname()), "www.")
	b := strings.TrimPrefix(strings.ToLower(host), "www.")
	return a == b
}

// thousands groups digits so a request count is readable at a glance.
func thousands(n int64) string {
	s := fmt.Sprintf("%d", n)
	var out []byte
	for i, c := range []byte(s) {
		if i > 0 && (len(s)-i)%3 == 0 {
			out = append(out, ',')
		}
		out = append(out, c)
	}
	return string(out)
}
