package main

import (
	"os"
	"regexp"
	"strings"
	"testing"
)

// The Go version is stated in four places that must agree: a Docker image built against an older
// toolchain than go.mod requires fails at build time, and a release built against a different one
// than CI tested is a different binary.
func TestGoVersionIsTheSameEverywhere(t *testing.T) {
	goMod := readDoc(t, "go.mod")
	m := regexp.MustCompile(`(?m)^go (\d+\.\d+)`).FindStringSubmatch(goMod)
	if m == nil {
		t.Fatal("go.mod has no go directive")
	}
	want := m[1]
	for _, f := range []string{".github/workflows/ci.yml", ".github/workflows/release.yml", "Dockerfile"} {
		if !strings.Contains(readDoc(t, f), want) {
			t.Errorf("%s does not use Go %s (go.mod does)", f, want)
		}
	}
}

func TestEveryDocumentedInstallMethodExists(t *testing.T) {
	// The README promises four ways in. A promise with no file behind it is the worst kind.
	readme := readDoc(t, "README.md")
	for _, c := range []struct{ promise, file string }{
		{"brew ", ".goreleaser.yaml"},
		{"docker run", "Dockerfile"},
		{"Releases", ".github/workflows/release.yml"},
		{"go install", "main.go"},
	} {
		if !strings.Contains(readme, c.promise) {
			t.Errorf("README.md does not document %q", c.promise)
			continue
		}
		if _, err := os.Stat(c.file); err != nil {
			t.Errorf("README.md documents %q but %s does not exist", c.promise, c.file)
		}
	}
}

// The cask that people install is generated by goreleaser and pushed to Allan-Nava/homebrew-tap,
// which is where every other Allan-Nava CLI lives. That tap's rule is "no formula, only casks, and
// nobody writes one by hand": a formula in this repo would be a second place where a version can be
// wrong, and the tap already has the drift detection this repo would have had to grow.
func TestTheCaskIsPublishedFromGoreleaser(t *testing.T) {
	g := readDoc(t, ".goreleaser.yaml")
	for _, want := range []string{
		"homebrew_casks",
		"homebrew-tap",              // the shared tap, not a self-tap
		"HOMEBREW_TAP_GITHUB_TOKEN", // the PAT that lets the release write there
		"com.apple.quarantine",      // ⚠️ unsigned binary: without this it dies on SIGKILL, silently
		"main.version=",             // or the installed binary reports "dev"
		`skip_upload: "auto"`,       // a prerelease must not become what `brew install` hands out
	} {
		if !strings.Contains(g, want) {
			t.Errorf(".goreleaser.yaml is missing %q", want)
		}
	}
	if _, err := os.Stat("Formula/robotsmith.rb"); err == nil {
		t.Error("Formula/robotsmith.rb is back: the cask on the tap is the only Homebrew path, " +
			"and a formula here is a second place for the version to go stale")
	}

	// The release notes still come from the CHANGELOG, and a missing section still stops the
	// release — that contract predates goreleaser and must survive it.
	r := readDoc(t, ".github/workflows/release.yml")
	for _, want := range []string{"goreleaser", "--release-notes", "CHANGELOG.md"} {
		if !strings.Contains(r, want) {
			t.Errorf("release.yml is missing %q", want)
		}
	}
}

func TestDockerImageRunsAsNobodyAndFromScratch(t *testing.T) {
	// This binary reads a file and makes two GET requests: it has no business owning a shell, a
	// package manager or root inside a container.
	d := readDoc(t, "Dockerfile")
	for _, want := range []string{"FROM scratch", "ca-certificates.crt", "USER 65534", "ENTRYPOINT"} {
		if !strings.Contains(d, want) {
			t.Errorf("Dockerfile is missing %q", want)
		}
	}
	if !strings.Contains(d, "CGO_ENABLED=0") {
		t.Error("a scratch image needs a static binary: CGO_ENABLED=0")
	}
	if _, err := os.Stat(".dockerignore"); err != nil {
		t.Error("without .dockerignore the build context carries the git history into the image build")
	}
}

// The formula is rewritten by a robot at tag time and installed by people days later: nobody ever
// runs `brew install` in between. This checks the loop is closed by a workflow, on a real macOS
// runner — a formula that only ever gets read is a formula that is only ever wrong in public.
func TestHomebrewInstallIsVerifiedByAWorkflow(t *testing.T) {
	w := readDoc(t, ".github/workflows/brew.yml")
	for _, want := range []string{
		"workflow_run", // it has to wait for the release: goreleaser pushes the cask at the end
		"schedule",     // and run again on a cron, because a tap rots without anybody releasing
		"macos-",       // plus Linux, but macOS is where the quarantine bit matters
		"brew install --cask",
		"Allan-Nava/tap/robotsmith",
		"HOMEBREW_NO_REQUIRE_TAP_TRUST", // ⚠️ Homebrew 6+ blocks a third-party tap interactively
		"releases/latest",               // ⚠️ the assertion that catches a tap left behind
		"no release yet",                // ⚠️ before the first tag there is no cask: skip, do not fail
	} {
		if !strings.Contains(w, want) {
			t.Errorf("brew.yml is missing %q", want)
		}
	}
}

func TestTheCompositeActionIsUsableAndDogfooded(t *testing.T) {
	// ⚠️ An action nobody runs is an action that is broken in public. This repo uses its own,
	// so a mistake in action.yml is a red check here before it is a red check for a stranger.
	a := readDoc(t, "action.yml")
	for _, want := range []string{
		"using: composite", // no Docker image to build on every run
		"command:",         // check | lint | advise | crawlers
		"target:",          // file or domain
		"version:",         // pin a release, or track the latest
		"--format",         // the tool decides the shape; the action passes it through
		"default: github",  // ...and annotations are the default: they are why this exists
		"checksums.txt",    // a downloaded binary is verified before it runs
		"awk",              // ⚠️ and its NAME is discovered from checksums.txt, not guessed:
		//                     hardcoding an archive template broke the action in public
		"outputs:", // so a later step can act on the verdict
	} {
		if !strings.Contains(a, want) {
			t.Errorf("action.yml is missing %q", want)
		}
	}
	if strings.Contains(a, "go install") && !strings.Contains(a, "fallback") {
		t.Error("if it can fall back to `go install`, say so: it needs a Go toolchain on the runner")
	}
	// The asset name must never be built from a template: the published names have changed once
	// already (tar.gz → raw binary, with the version embedded) and that 404 was invisible until
	// somebody ran the action.
	for _, guessed := range []string{"robotsmith_${os}_${arch}", ".tar.gz\"", "_${VERSION}_"} {
		if strings.Contains(a, guessed) {
			t.Errorf("action.yml builds the asset name from a template (%q): derive it from "+
				"checksums.txt instead, which lists what was actually published", guessed)
		}
	}
	// macOS runners have shasum, not sha256sum: assuming one of them fails on half the runners.
	if strings.Contains(a, "sha256sum") && !strings.Contains(a, "shasum") {
		t.Error("verification must work on macOS runners too, where the tool is `shasum -a 256`")
	}

	ci := readDoc(t, ".github/workflows/ci.yml")
	if !strings.Contains(ci, "uses: ./") {
		t.Error("ci.yml must run the action from this checkout: an untested action is a broken one")
	}

	// The README is where somebody copies it from, and the docs gate cannot see YAML snippets.
	readme := readDoc(t, "README.md")
	if !strings.Contains(readme, "uses: Allan-Nava/robotsmith@") {
		t.Error("README.md must show the three-line snippet, or nobody knows the action exists")
	}
}

func TestTheReleaseBuildsFromACleanTree(t *testing.T) {
	// ⚠️ The version string reports whether the tree was dirty, so anything the release writes
	// INTO the checkout before building ends up stamped into the published binary: v0.2.0 and
	// v0.3.0 both went out saying "dirty" because the release notes were written next to the code.
	r := readDoc(t, ".github/workflows/release.yml")
	if strings.Contains(r, "> notes.md") || strings.Contains(r, "--notes-file notes.md") {
		t.Error("release.yml writes notes.md into the checkout: use $RUNNER_TEMP, or the binary " +
			"claims to be built from a modified tree")
	}
	if !strings.Contains(r, "RUNNER_TEMP") {
		t.Error("scratch files belong in $RUNNER_TEMP")
	}
}
