package main

import (
	"bytes"
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// serveRobots exposes a robots.txt on a local server: no test in this repo touches the network.
func serveRobots(t *testing.T, body string, status int) string {
	t.Helper()
	s := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(status)
		_, _ = w.Write([]byte(body))
	}))
	t.Cleanup(s.Close)
	return s.URL + "/robots.txt"
}

// healthyRobots passes every expected case: whoever brings visits gets through, whoever takes
// without giving does not.
const healthyRobots = `User-agent: Googlebot
User-agent: Google-InspectionTool
User-agent: Storebot-Google
User-agent: bingbot
User-agent: DuckDuckBot
User-agent: Applebot
User-agent: facebookexternalhit
User-agent: Twitterbot
User-agent: LinkedInBot
User-agent: WhatsApp
User-agent: TelegramBot
User-agent: Slackbot
User-agent: Discordbot
User-agent: Pinterest
User-agent: ChatGPT-User
User-agent: OAI-SearchBot
Allow: /

User-agent: YisouSpider
User-agent: GPTBot
User-agent: CCBot
User-agent: ClaudeBot
User-agent: anthropic-ai
User-agent: PerplexityBot
User-agent: Bytespider
User-agent: Amazonbot
User-agent: meta-externalagent
User-agent: SemrushBot
User-agent: AhrefsBot
User-agent: MJ12bot
User-agent: DotBot
User-agent: BLEXBot
User-agent: DataForSeoBot
Disallow: /

User-agent: *
Disallow: /admin/
`

// runCLI drives the whole CLI the way a pipeline does: arguments in, exit code and the two streams
// out. The exit codes are a documented contract, so they are asserted case by case.
func runCLI(args ...string) (code int, stdout, stderr string) {
	var o, e bytes.Buffer
	code = run(args, &o, &e)
	return code, o.String(), e.String()
}

func TestExitCodeContract(t *testing.T) {
	good := writeTemp(t, "robots.txt", "User-agent: *\nDisallow: /admin/\n")
	broken := writeTemp(t, "broken.txt", "User-agent: *\n\nDisallow: /admin/\n")
	warned := writeTemp(t, "warned.txt", "User-agent: *\nAllow: /\nDisallow: /login\n")
	missing := filepath.Join(t.TempDir(), "nope.txt")

	cases := []struct {
		name string
		args []string
		want int
	}{
		{"no arguments at all", nil, 2},
		{"unknown subcommand", []string{"frobnicate"}, 2},
		{"lint with no file", []string{"lint"}, 2},
		{"lint on a clean file", []string{"lint", good}, 0},
		{"lint on a warning-only file", []string{"lint", warned}, 0},
		{"lint on a structural error", []string{"lint", broken}, 1},
		{"lint --strict on a warning", []string{"lint", "--strict", warned}, 1},
		{"lint on a missing file", []string{"lint", missing}, 4},
		{"check with no target", []string{"check"}, 2},
		{"check on a healthy file", []string{"check", serveRobots(t, healthyRobots, 200)}, 0},
		{"check on a deindexing file", []string{"check", serveRobots(t, "User-agent: *\nDisallow: /\n", 200)}, 1},
		{"check on a 404", []string{"check", serveRobots(t, "gone", 404)}, 4},
		{"advise with no input", []string{"advise"}, 2},
		{"advise on a missing count file", []string{"advise", "--ua-counts", missing}, 4},
		{"unknown flag", []string{"lint", "--nope", good}, 2},
		{"version", []string{"version"}, 0},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			got, _, _ := runCLI(c.args...)
			if got != c.want {
				t.Errorf("exit code = %d, expected %d", got, c.want)
			}
		})
	}
}

func TestAdviseWritesTheFileOnStdoutAndTheReasoningOnStderr(t *testing.T) {
	// `robotsmith advise … > robots.txt` must produce a clean file: not one byte of prose on stdout.
	counts := writeTemp(t, "ua.txt", "5000 Mozilla/5.0 (compatible; GPTBot/1.4)\n1000 Mozilla/5.0 (compatible; Googlebot/2.1)\n")
	code, stdout, stderr := runCLI("advise", "--ua-counts", counts, "--host", "example.com")
	if code != 0 {
		t.Fatalf("exit code = %d, expected 0. stderr: %s", code, stderr)
	}
	if !strings.HasPrefix(stdout, "# robots.txt generated by robotsmith") {
		t.Errorf("stdout must start with the generated file, got:\n%s", stdout)
	}
	if strings.Contains(stdout, "What I advise") {
		t.Error("the reasoning must not end up in the file")
	}
	if !strings.Contains(stderr, "What I advise") {
		t.Error("the reasoning must be on stderr, where a human reads it")
	}
}

func TestAdviseOutWritesTheFileAndKeepsStdoutEmpty(t *testing.T) {
	counts := writeTemp(t, "ua.txt", "5000 Mozilla/5.0 (compatible; GPTBot/1.4)\n")
	dest := filepath.Join(t.TempDir(), "robots.txt")
	code, stdout, _ := runCLI("advise", "--ua-counts", counts, "--out", dest)
	if code != 0 {
		t.Fatalf("exit code = %d", code)
	}
	if stdout != "" {
		t.Errorf("with --out nothing goes to stdout, got %q", stdout)
	}
	b, err := os.ReadFile(dest)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(b), "User-agent: GPTBot") {
		t.Errorf("the written file must contain the advice:\n%s", b)
	}
}

func TestJSONOutputIsValidAndCarriesItsSchema(t *testing.T) {
	// A pipeline pins the schema: it is the only stable promise, because the prose is free to change.
	counts := writeTemp(t, "ua.txt", "5000 Mozilla/5.0 (compatible; GPTBot/1.4)\n1000 Mozilla/5.0 (compatible; Googlebot/2.1)\n")
	broken := writeTemp(t, "broken.txt", "User-agent: *\n\nDisallow: /admin/\n")

	cases := []struct {
		name   string
		args   []string
		schema string
	}{
		{"check", []string{"check", "--json", serveRobots(t, healthyRobots, 200)}, "robotsmith.check/1"},
		{"lint", []string{"lint", "--json", broken}, "robotsmith.lint/1"},
		{"advise", []string{"advise", "--json", "--ua-counts", counts}, "robotsmith.advise/1"},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			_, stdout, _ := runCLI(c.args...)
			var got map[string]any
			if err := json.Unmarshal([]byte(stdout), &got); err != nil {
				t.Fatalf("stdout is not valid JSON: %v\n%s", err, stdout)
			}
			if got["schema"] != c.schema {
				t.Errorf("schema = %v, expected %s", got["schema"], c.schema)
			}
		})
	}
}

func TestJSONKeepsTheExitCodeAndStdoutJSONOnly(t *testing.T) {
	// --json changes the shape of the answer, never the verdict.
	code, stdout, _ := runCLI("lint", "--json", writeTemp(t, "broken.txt", "User-agent: *\n\nDisallow: /a\n"))
	if code != 1 {
		t.Errorf("exit code = %d, expected 1: --json must not soften the verdict", code)
	}
	var rep struct {
		OK       bool `json:"ok"`
		Errors   int  `json:"errors"`
		Findings []struct {
			Severity string `json:"severity"`
			Line     int    `json:"line"`
		} `json:"findings"`
	}
	if err := json.Unmarshal([]byte(stdout), &rep); err != nil {
		t.Fatal(err)
	}
	if rep.OK || rep.Errors != 1 || len(rep.Findings) != 1 {
		t.Errorf("report = %+v", rep)
	}
	if rep.Findings[0].Severity != "ERROR" || rep.Findings[0].Line != 3 {
		t.Errorf("finding = %+v: severity and line are what a CI annotation needs", rep.Findings[0])
	}
}

func TestAdviseJSONCarriesTheFileAndTheDecisions(t *testing.T) {
	counts := writeTemp(t, "ua.txt", "5000 Mozilla/5.0 (compatible; GPTBot/1.4)\n1000 Mozilla/5.0 (compatible; Googlebot/2.1)\n")
	_, stdout, _ := runCLI("advise", "--json", "--ua-counts", counts)
	var rep struct {
		Total     int64  `json:"total_requests"`
		RobotsTxt string `json:"robots_txt"`
		Decisions []struct {
			Name   string  `json:"name"`
			Family string  `json:"family"`
			Policy string  `json:"policy"`
			Share  float64 `json:"share"`
		} `json:"decisions"`
	}
	if err := json.Unmarshal([]byte(stdout), &rep); err != nil {
		t.Fatal(err)
	}
	if rep.Total != 6000 {
		t.Errorf("total_requests = %d, expected 6000", rep.Total)
	}
	if !strings.Contains(rep.RobotsTxt, "User-agent: GPTBot") {
		t.Error("the advised file must travel inside the JSON: a consumer must not have to run twice")
	}
	byName := map[string]string{}
	for _, d := range rep.Decisions {
		byName[d.Name] = d.Policy
	}
	if byName["GPTBot"] != "block" || byName["Googlebot"] != "allow" {
		t.Errorf("policies = %v", byName)
	}
}

func TestCrawlersCommandPrintsTheWholeTable(t *testing.T) {
	// The policy table is the opinionated core of this tool. Someone deciding whether to trust it
	// has to be able to read it without opening the source.
	code, stdout, _ := runCLI("crawlers")
	if code != 0 {
		t.Fatalf("exit code = %d", code)
	}
	for _, want := range []string{"Googlebot", "GPTBot", "ChatGPT-User", "ALLOW", "BLOCK", "REVIEW",
		"ai-training", "brings visits"} {
		if !strings.Contains(stdout, want) {
			t.Errorf("the listing is missing %q", want)
		}
	}
	// Rules with no robots.txt token (browsers, monitors) are the ones robots.txt cannot address:
	// they must be visible as such, not silently dropped from the listing.
	if !strings.Contains(stdout, "IGNORE") {
		t.Error("the families robots.txt does not address must appear too, marked as ignored")
	}
	// ⚠️ An unknown crawler HAS no token in the table but is perfectly addressable: the token is
	// derived from its UA at runtime. Calling it "not addressable" would be wrong.
	if !strings.Contains(stdout, "derived from the UA") {
		t.Error("the unknown catch-all must say its token is derived from the observed UA")
	}
}

func TestCrawlersJSONIsOrderedLikeTheEvaluation(t *testing.T) {
	// The first matching pattern wins, so the order IS part of the answer: a consumer must get it
	// in evaluation order, not sorted for looks.
	_, stdout, _ := runCLI("crawlers", "--json")
	var rep struct {
		Schema string `json:"schema"`
		Rules  []struct {
			Pattern string `json:"pattern"`
			Family  string `json:"family"`
			Policy  string `json:"policy"`
			Token   string `json:"token"`
		} `json:"rules"`
	}
	if err := json.Unmarshal([]byte(stdout), &rep); err != nil {
		t.Fatalf("not valid JSON: %v\n%s", err, stdout)
	}
	if rep.Schema != "robotsmith.crawlers/1" {
		t.Errorf("schema = %q", rep.Schema)
	}
	if len(rep.Rules) < 40 {
		t.Fatalf("expected the whole table, got %d rules", len(rep.Rules))
	}
	if rep.Rules[0].Token != "Googlebot" {
		t.Errorf("first rule = %+v: the allowlist must come first, or a generic pattern swallows it",
			rep.Rules[0])
	}
	var iGPTBot, iChatGPTUser int
	for i, r := range rep.Rules {
		switch r.Token {
		case "GPTBot":
			iGPTBot = i
		case "ChatGPT-User":
			iChatGPTUser = i
		}
	}
	if iChatGPTUser > iGPTBot {
		t.Error("ChatGPT-User must be listed before GPTBot: their UA contains \"openai\" and the " +
			"order is what keeps a user-triggered fetch out of the training bucket")
	}
}

func TestAdviseDiffShowsOnlyWhatWouldChange(t *testing.T) {
	counts := writeTemp(t, "ua.txt", "2000 Mozilla/5.0 (compatible; Googlebot/2.1)\n1000 Mozilla/5.0 (compatible; GPTBot/1.4)\n")
	current := writeTemp(t, "robots.txt", "User-agent: Googlebot\nAllow: /\n\nUser-agent: YandexBot\nDisallow: /search\n\nUser-agent: *\nDisallow: /admin/\n")

	code, stdout, _ := runCLI("advise", "--ua-counts", counts, "--current", current, "--diff")
	if code != 0 {
		t.Fatalf("exit code = %d", code)
	}
	if !strings.Contains(stdout, "GPTBot") || !strings.Contains(stdout, "+") {
		t.Errorf("the added block must be visible:\n%s", stdout)
	}
	if !strings.Contains(stdout, "YandexBot") {
		t.Errorf("the group carried over verbatim must be named — silence is how a rule gets lost:\n%s", stdout)
	}
	// A diff is a review aid, not a file: it must not be mistaken for one.
	if strings.Contains(stdout, "# robots.txt generated by robotsmith") {
		t.Error("--diff must print the review, not the file")
	}
}

func TestAdviseDiffSaysSoWhenNothingWouldChange(t *testing.T) {
	counts := writeTemp(t, "ua.txt", "1000 Mozilla/5.0 (compatible; GPTBot/1.4)\n")
	current := writeTemp(t, "robots.txt", "User-agent: GPTBot\nDisallow: /\n\nUser-agent: *\nDisallow: /admin/\n")
	code, stdout, _ := runCLI("advise", "--ua-counts", counts, "--current", current, "--diff")
	if code != 0 {
		t.Fatalf("exit code = %d", code)
	}
	if !strings.Contains(strings.ToLower(stdout), "nothing to change") {
		t.Errorf("an empty diff must say so in one line:\n%s", stdout)
	}
}

func TestAdviseShowsTheEvidenceBehindAReviewDecision(t *testing.T) {
	// A share is a snapshot; the decision needs the shape of the traffic. This is only possible
	// from a real log, which is why it is not offered for --ua-counts.
	var log strings.Builder
	for i := 0; i < 30; i++ {
		log.WriteString(`1.1.1.1 - - [01/Sep/2026:1` + string(rune('0'+i%10)) +
			`:00:00 +0000] "GET /archive/page HTTP/1.1" 200 1 "-" "Mozilla/5.0 (compatible; SomeSpider/1.0)"` + "\n")
	}
	for i := 0; i < 70; i++ {
		log.WriteString(`2.2.2.2 - - [01/Sep/2026:12:00:00 +0000] "GET / HTTP/1.1" 200 1 "-" "Mozilla/5.0 (Windows NT 10.0) Chrome/148"` + "\n")
	}
	p := writeTemp(t, "access.log", log.String())

	code, _, stderr := runCLI("advise", "--log", p)
	if code != 0 {
		t.Fatalf("exit code = %d, stderr: %s", code, stderr)
	}
	if !strings.Contains(stderr, "REVIEW") || !strings.Contains(stderr, "SomeSpider") {
		t.Fatalf("SomeSpider is 30%% of the traffic and unknown: it must come up for review:\n%s", stderr)
	}
	if !strings.Contains(stderr, "/archive/page") {
		t.Errorf("the paths it asked for are the argument, and must be shown:\n%s", stderr)
	}
	if !strings.Contains(stderr, "over") {
		t.Errorf("the time span must be shown: a crawl spread over hours is not a burst:\n%s", stderr)
	}
}

func TestAdviseFromCountsClaimsNoEvidence(t *testing.T) {
	counts := writeTemp(t, "ua.txt", "3000 Mozilla/5.0 (compatible; SomeSpider/1.0)\n7000 Mozilla/5.0 (Windows NT 10.0) Chrome/148\n")
	_, _, stderr := runCLI("advise", "--ua-counts", counts)
	if !strings.Contains(stderr, "SomeSpider") {
		t.Fatalf("stderr:\n%s", stderr)
	}
	if strings.Contains(stderr, "asked for") {
		t.Error("a count file has no paths: the tool must not pretend otherwise")
	}
}

func TestGitHubFormatEmitsAnnotationsAndKeepsTheVerdict(t *testing.T) {
	broken := writeTemp(t, "robots.txt", "User-agent: *\n\nDisallow: /admin/\n")
	code, stdout, _ := runCLI("lint", "--format", "github", broken)
	if code != 1 {
		t.Errorf("exit code = %d, expected 1: the output format never changes the verdict", code)
	}
	if !strings.HasPrefix(stdout, "::error file=") {
		t.Fatalf("stdout must be workflow commands:\n%s", stdout)
	}
	if !strings.Contains(stdout, "line=3") {
		t.Errorf("the annotation must land on the defective line:\n%s", stdout)
	}
	if strings.Contains(stdout, "\n\n") {
		t.Errorf("one command per line, nothing else:\n%q", stdout)
	}
}

func TestFormatJSONIsTheSameAsTheJSONFlag(t *testing.T) {
	// --json shipped in 0.2.0 and stays: --format json is the same thing said the new way.
	broken := writeTemp(t, "robots.txt", "User-agent: *\n\nDisallow: /a\n")
	_, viaFlag, _ := runCLI("lint", "--json", broken)
	_, viaFormat, _ := runCLI("lint", "--format", "json", broken)
	if viaFlag != viaFormat {
		t.Errorf("--json and --format json must produce the same document:\n%s\n---\n%s", viaFlag, viaFormat)
	}
}

func TestAnUnknownFormatIsAUsageError(t *testing.T) {
	// Silently falling back to text would hide a typo in a pipeline for as long as nobody reads it.
	code, _, stderr := runCLI("lint", "--format", "yaml", writeTemp(t, "robots.txt", "User-agent: *\nDisallow:\n"))
	if code != 2 {
		t.Errorf("exit code = %d, expected 2 (usage error)", code)
	}
	if !strings.Contains(stderr, "text") || !strings.Contains(stderr, "github") {
		t.Errorf("the error must list what is valid: %q", stderr)
	}
}

func TestCheckSpeaksGitHubToo(t *testing.T) {
	code, stdout, _ := runCLI("check", "--format", "github", serveRobots(t, "User-agent: *\nDisallow: /\n", 200))
	if code != 1 {
		t.Errorf("exit code = %d, expected 1", code)
	}
	if !strings.Contains(stdout, "::error") || !strings.Contains(stdout, "Googlebot") {
		t.Errorf("a blocked search engine must be annotated:\n%s", stdout)
	}
}

func TestACleanRunAnnotatesNothingAndSaysSo(t *testing.T) {
	// An empty stdout with exit 0 is correct but reads like a silent failure in a log: one line
	// costs nothing and tells whoever is scrolling that the check ran.
	code, stdout, stderr := runCLI("lint", "--format", "github", writeTemp(t, "robots.txt", "User-agent: *\nDisallow: /admin/\n"))
	if code != 0 {
		t.Fatalf("exit code = %d", code)
	}
	if strings.Contains(stdout, "::error") || strings.Contains(stdout, "::warning") {
		t.Errorf("nothing to annotate:\n%s", stdout)
	}
	if !strings.Contains(stdout+stderr, "no structural defect") {
		t.Errorf("it must still say it ran:\nstdout %q\nstderr %q", stdout, stderr)
	}
}

func TestPolicyFileOverridesTheBuiltInAdviceAndSaysSo(t *testing.T) {
	counts := writeTemp(t, "ua.txt", "5000 Mozilla/5.0 (compatible; Bytespider)\n5000 Mozilla/5.0 (compatible; Googlebot/2.1)\n")
	pol := writeTemp(t, "policy.json", `{"schema":"robotsmith.policy/1","rules":[
	  {"pattern":"bytespider","policy":"allow","why":"we license our content to them"}
	]}`)
	code, stdout, stderr := runCLI("advise", "--ua-counts", counts, "--policy", pol)
	if code != 0 {
		t.Fatalf("exit code = %d, stderr: %s", code, stderr)
	}
	if !strings.Contains(stderr, "we license our content to them") {
		t.Errorf("the file's own reason must appear in the reasoning:\n%s", stderr)
	}
	if !strings.Contains(stderr, "policy.json") {
		t.Errorf("the reasoning must say the answer came from the file, and which one:\n%s", stderr)
	}
	if strings.Contains(stdout, "User-agent: Bytespider\nDisallow: /") {
		t.Error("Bytespider must no longer be blocked in the generated file")
	}
	if !strings.Contains(stdout, "User-agent: Bytespider\nAllow: /") {
		t.Errorf("it must be allowed explicitly instead:\n%s", stdout)
	}
}

func TestABrokenPolicyFileIsAUsageErrorNotAWarning(t *testing.T) {
	// ⚠️ Falling back to the defaults would apply an opinion the site explicitly rejected, quietly.
	counts := writeTemp(t, "ua.txt", "10 Mozilla/5.0 (compatible; GPTBot/1.4)\n")
	bad := writeTemp(t, "policy.json", `{"schema":"robotsmith.policy/1","rules":[{"pattern":"x","policy":"maybe"}]}`)
	code, _, stderr := runCLI("advise", "--ua-counts", counts, "--policy", bad)
	if code != 2 {
		t.Errorf("exit code = %d, expected 2 (usage error)", code)
	}
	if !strings.Contains(stderr, "maybe") || !strings.Contains(stderr, "rules[0]") {
		t.Errorf("the error must be actionable: %q", stderr)
	}
}

func TestAMissingPolicyFileIsNotSilentlyIgnored(t *testing.T) {
	counts := writeTemp(t, "ua.txt", "10 Mozilla/5.0 (compatible; GPTBot/1.4)\n")
	code, _, stderr := runCLI("advise", "--ua-counts", counts, "--policy", filepath.Join(t.TempDir(), "nope.json"))
	if code != 4 {
		t.Errorf("exit code = %d, expected 4 (file unreachable)", code)
	}
	if !strings.Contains(stderr, "nope.json") {
		t.Errorf("stderr = %q", stderr)
	}
}

func TestPolicyReachesTheJSONDocument(t *testing.T) {
	counts := writeTemp(t, "ua.txt", "10 Mozilla/5.0 (compatible; Bytespider)\n")
	pol := writeTemp(t, "policy.json", `{"schema":"robotsmith.policy/1","rules":[{"pattern":"bytespider","policy":"allow"}]}`)
	_, stdout, _ := runCLI("advise", "--json", "--ua-counts", counts, "--policy", pol)
	var rep struct {
		Decisions []struct {
			Name       string `json:"name"`
			Policy     string `json:"policy"`
			Rule       string `json:"rule"`
			FromPolicy bool   `json:"from_policy_file"`
		} `json:"decisions"`
	}
	if err := json.Unmarshal([]byte(stdout), &rep); err != nil {
		t.Fatal(err)
	}
	if len(rep.Decisions) != 1 {
		t.Fatalf("decisions = %+v", rep.Decisions)
	}
	d := rep.Decisions[0]
	if d.Policy != "allow" || d.Rule != "bytespider" || !d.FromPolicy {
		t.Errorf("decision = %+v: a consumer must be able to tell an override from a default", d)
	}
}

func TestCheckExpectClosesTheLoop(t *testing.T) {
	// The same file that drives `advise --policy` verifies what got deployed.
	served := "User-agent: Bytespider\nAllow: /\n\nUser-agent: *\nDisallow: /admin/\n"
	pol := writeTemp(t, "policy.json", `{"schema":"robotsmith.policy/1","rules":[
	  {"pattern":"bytespider","policy":"allow","why":"we license our content to them"},
	  {"pattern":"gptbot","policy":"block","why":"takes without giving"},
	  {"pattern":"semrush","policy":"ignore","why":"our own team runs it"}
	]}`)
	code, stdout, _ := runCLI("check", "--expect", pol, serveRobots(t, served, 200))
	if code != 1 {
		t.Errorf("exit code = %d, expected 1: gptbot is not blocked by the deployed file", code)
	}
	if !strings.Contains(stdout, "bytespider") || !strings.Contains(stdout, "Allow: /") {
		t.Errorf("a met expectation must show the line that meets it:\n%s", stdout)
	}
	if !strings.Contains(stdout, "gptbot") || !strings.Contains(stdout, "inherited from") {
		t.Errorf("the divergence must say the answer came from the `*` group:\n%s", stdout)
	}
	if strings.Contains(stdout, "semrush") {
		t.Error("an `ignore` rule is not an assertion: there is nothing to verify")
	}
	if !strings.Contains(stdout, "takes without giving") {
		t.Errorf("the reason the expectation was written must be shown, so a reader knows whether to "+
			"fix the file or the expectation:\n%s", stdout)
	}
}

func TestCheckExpectPassesWhenTheFileAgrees(t *testing.T) {
	served := "User-agent: bytespider\nAllow: /\n\nUser-agent: gptbot\nDisallow: /\n\nUser-agent: *\nDisallow:\n"
	pol := writeTemp(t, "policy.json", `{"schema":"robotsmith.policy/1","rules":[
	  {"pattern":"bytespider","policy":"allow"},
	  {"pattern":"gptbot","policy":"block"}
	]}`)
	code, stdout, _ := runCLI("check", "--expect", pol, serveRobots(t, served, 200))
	if code != 0 {
		t.Errorf("exit code = %d, expected 0. stdout:\n%s", code, stdout)
	}
}

func TestCheckExpectCannotSynthesiseAUAFromARegex(t *testing.T) {
	// ⚠️ A pattern like `youbot|diffbot` is a fine matching rule and a nonsense user-agent. Testing
	// it as a literal would produce a confident, meaningless verdict.
	pol := writeTemp(t, "policy.json", `{"schema":"robotsmith.policy/1","rules":[{"pattern":"youbot|diffbot","policy":"block"}]}`)
	code, stdout, stderr := runCLI("check", "--expect", pol, serveRobots(t, "User-agent: *\nDisallow:\n", 200))
	if code != 0 {
		t.Errorf("exit code = %d: nothing verifiable was asked for", code)
	}
	if !strings.Contains(stderr+stdout, "youbot|diffbot") {
		t.Errorf("skipping must be said out loud:\n%s\n%s", stdout, stderr)
	}
}

func TestCheckExpectReachesTheJSONDocument(t *testing.T) {
	pol := writeTemp(t, "policy.json", `{"schema":"robotsmith.policy/1","rules":[{"pattern":"gptbot","policy":"block","why":"no visits"}]}`)
	_, stdout, _ := runCLI("check", "--json", "--expect", pol, serveRobots(t, "User-agent: *\nDisallow:\n", 200))
	var rep struct {
		Expected []struct {
			UA      string `json:"user_agent"`
			Want    bool   `json:"want_allowed"`
			Got     bool   `json:"got_allowed"`
			Met     bool   `json:"met"`
			Why     string `json:"why"`
			ViaStar bool   `json:"via_star"`
		} `json:"expected"`
	}
	if err := json.Unmarshal([]byte(stdout), &rep); err != nil {
		t.Fatal(err)
	}
	if len(rep.Expected) != 1 {
		t.Fatalf("expected = %+v", rep.Expected)
	}
	e := rep.Expected[0]
	if e.UA != "gptbot" || e.Want || !e.Got || e.Met || e.Why != "no visits" || !e.ViaStar {
		t.Errorf("expected = %+v", e)
	}
}

func TestAdviseCompareReportsTheMovement(t *testing.T) {
	// A stored --json document is the previous run: no new file format to learn.
	prev := writeTemp(t, "prev.json", `{
	  "schema": "robotsmith.advise/1",
	  "total_requests": 100000,
	  "decisions": [
	    {"name":"GPTBot","policy":"block","requests":2000,"share":2.0},
	    {"name":"OldBot","policy":"block","requests":3000,"share":3.0}
	  ]
	}`)
	counts := writeTemp(t, "ua.txt", "8000 Mozilla/5.0 (compatible; GPTBot/1.4)\n92000 Mozilla/5.0 (Windows NT 10.0) Chrome/148\n")
	code, _, stderr := runCLI("advise", "--ua-counts", counts, "--compare", prev)
	if code != 0 {
		t.Fatalf("exit code = %d, stderr: %s", code, stderr)
	}
	if !strings.Contains(stderr, "GPTBot") || !strings.Contains(stderr, "grew") {
		t.Errorf("GPTBot went 2%% → 8%%: that must be reported as growth:\n%s", stderr)
	}
	if !strings.Contains(stderr, "OldBot") || !strings.Contains(stderr, "vanished") {
		t.Errorf("a crawler that stopped coming must be reported: a rule still blocking it is "+
			"stale and nobody notices a rule that does nothing:\n%s", stderr)
	}
}

func TestAdviseCompareRefusesAWrongDocument(t *testing.T) {
	counts := writeTemp(t, "ua.txt", "10 Mozilla/5.0 (compatible; GPTBot/1.4)\n")
	for name, body := range map[string]string{
		"a lint document": `{"schema":"robotsmith.lint/1","findings":[]}`,
		"a future schema": `{"schema":"robotsmith.advise/9","decisions":[]}`,
		"not a document":  `{}`,
	} {
		t.Run(name, func(t *testing.T) {
			bad := writeTemp(t, "prev.json", body)
			code, _, stderr := runCLI("advise", "--ua-counts", counts, "--compare", bad)
			if code != 2 {
				t.Errorf("exit code = %d, expected 2: comparing against the wrong document would "+
					"invent a trend", code)
			}
			if stderr == "" {
				t.Error("it must say why")
			}
		})
	}
}

func TestAdviseCompareReachesTheJSONDocument(t *testing.T) {
	prev := writeTemp(t, "prev.json", `{"schema":"robotsmith.advise/1","total_requests":100000,
	  "decisions":[{"name":"GPTBot","policy":"block","requests":2000,"share":2.0}]}`)
	counts := writeTemp(t, "ua.txt", "8000 Mozilla/5.0 (compatible; GPTBot/1.4)\n92000 Mozilla/5.0 (Windows NT 10.0) Chrome/148\n")
	_, stdout, _ := runCLI("advise", "--json", "--ua-counts", counts, "--compare", prev)
	var rep struct {
		Comparison *struct {
			PreviousTotal int64 `json:"previous_total_requests"`
			Movements     []struct {
				Name      string  `json:"name"`
				Direction string  `json:"direction"`
				Was       float64 `json:"was_share"`
				Now       float64 `json:"now_share"`
				Factor    float64 `json:"factor"`
			} `json:"movements"`
		} `json:"comparison"`
	}
	if err := json.Unmarshal([]byte(stdout), &rep); err != nil {
		t.Fatal(err)
	}
	if rep.Comparison == nil || rep.Comparison.PreviousTotal != 100000 {
		t.Fatalf("comparison = %+v", rep.Comparison)
	}
	var found bool
	for _, m := range rep.Comparison.Movements {
		if m.Name != "GPTBot" {
			continue
		}
		found = true
		if m.Direction != "grew" || m.Was != 2.0 || m.Now != 8.0 || m.Factor != 4.0 {
			t.Errorf("movement = %+v", m)
		}
	}
	if !found {
		t.Errorf("movements = %+v", rep.Comparison.Movements)
	}
}

func TestAdviseWritesAReportTheExtensionChooses(t *testing.T) {
	counts := writeTemp(t, "ua.txt", "5000 Mozilla/5.0 (compatible; GPTBot/1.4)\n5000 Mozilla/5.0 (compatible; Googlebot/2.1)\n")
	dir := t.TempDir()
	for _, name := range []string{"report.html", "report.pdf"} {
		dest := filepath.Join(dir, name)
		code, stdout, stderr := runCLI("advise", "--ua-counts", counts, "--host", "example.com", "--report", dest)
		if code != 0 {
			t.Fatalf("%s: exit %d, stderr: %s", name, code, stderr)
		}
		b, err := os.ReadFile(dest)
		if err != nil {
			t.Fatalf("%s: %v", name, err)
		}
		if len(b) < 500 {
			t.Errorf("%s is %d bytes: suspiciously empty", name, len(b))
		}
		if !strings.Contains(stderr, dest) {
			t.Errorf("%s: writing a file must be said out loud:\n%s", name, stderr)
		}
		// ⚠️ The report is an extra, not a replacement: stdout stays the file you deploy, so
		// `advise --report r.html > robots.txt` keeps working.
		if !strings.HasPrefix(stdout, "# robots.txt generated by robotsmith") {
			t.Errorf("%s: stdout must still be the robots.txt:\n%s", name, stdout)
		}
	}
	if b, _ := os.ReadFile(filepath.Join(dir, "report.pdf")); !bytes.HasPrefix(b, []byte("%PDF")) {
		t.Error("the .pdf must actually be a PDF")
	}
	if b, _ := os.ReadFile(filepath.Join(dir, "report.html")); !bytes.Contains(b, []byte("<svg")) {
		t.Error("the .html must carry the inline chart")
	}
}

func TestAnUnknownReportExtensionIsAUsageError(t *testing.T) {
	// Writing an HTML file called .docx because we guessed would be worse than refusing.
	counts := writeTemp(t, "ua.txt", "10 Mozilla/5.0 (compatible; GPTBot/1.4)\n")
	code, _, stderr := runCLI("advise", "--ua-counts", counts, "--report", filepath.Join(t.TempDir(), "r.docx"))
	if code != 2 {
		t.Errorf("exit code = %d, expected 2", code)
	}
	if !strings.Contains(stderr, ".html") || !strings.Contains(stderr, ".pdf") {
		t.Errorf("the error must say what is supported: %q", stderr)
	}
}
