package main

import (
	"bytes"
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// serveRobots exposes a robots.txt on a local server: no test in this repo touches the network.
func serveRobots(t *testing.T, body string, status int) string {
	t.Helper()
	s := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(status)
		_, _ = w.Write([]byte(body))
	}))
	t.Cleanup(s.Close)
	return s.URL + "/robots.txt"
}

// healthyRobots passes every expected case: whoever brings visits gets through, whoever takes
// without giving does not.
const healthyRobots = `User-agent: Googlebot
User-agent: Google-InspectionTool
User-agent: Storebot-Google
User-agent: bingbot
User-agent: DuckDuckBot
User-agent: Applebot
User-agent: facebookexternalhit
User-agent: Twitterbot
User-agent: LinkedInBot
User-agent: WhatsApp
User-agent: TelegramBot
User-agent: Slackbot
User-agent: Discordbot
User-agent: Pinterest
User-agent: ChatGPT-User
User-agent: OAI-SearchBot
Allow: /

User-agent: YisouSpider
User-agent: GPTBot
User-agent: CCBot
User-agent: ClaudeBot
User-agent: anthropic-ai
User-agent: PerplexityBot
User-agent: Bytespider
User-agent: Amazonbot
User-agent: meta-externalagent
User-agent: SemrushBot
User-agent: AhrefsBot
User-agent: MJ12bot
User-agent: DotBot
User-agent: BLEXBot
User-agent: DataForSeoBot
Disallow: /

User-agent: *
Disallow: /admin/
`

// runCLI drives the whole CLI the way a pipeline does: arguments in, exit code and the two streams
// out. The exit codes are a documented contract, so they are asserted case by case.
func runCLI(args ...string) (code int, stdout, stderr string) {
	var o, e bytes.Buffer
	code = run(args, &o, &e)
	return code, o.String(), e.String()
}

func TestExitCodeContract(t *testing.T) {
	good := writeTemp(t, "robots.txt", "User-agent: *\nDisallow: /admin/\n")
	broken := writeTemp(t, "broken.txt", "User-agent: *\n\nDisallow: /admin/\n")
	warned := writeTemp(t, "warned.txt", "User-agent: *\nAllow: /\nDisallow: /login\n")
	missing := filepath.Join(t.TempDir(), "nope.txt")

	cases := []struct {
		name string
		args []string
		want int
	}{
		{"no arguments at all", nil, 2},
		{"unknown subcommand", []string{"frobnicate"}, 2},
		{"lint with no file", []string{"lint"}, 2},
		{"lint on a clean file", []string{"lint", good}, 0},
		{"lint on a warning-only file", []string{"lint", warned}, 0},
		{"lint on a structural error", []string{"lint", broken}, 1},
		{"lint --strict on a warning", []string{"lint", "--strict", warned}, 1},
		{"lint on a missing file", []string{"lint", missing}, 4},
		{"check with no target", []string{"check"}, 2},
		{"check on a healthy file", []string{"check", serveRobots(t, healthyRobots, 200)}, 0},
		{"check on a deindexing file", []string{"check", serveRobots(t, "User-agent: *\nDisallow: /\n", 200)}, 1},
		{"check on a 404", []string{"check", serveRobots(t, "gone", 404)}, 4},
		{"advise with no input", []string{"advise"}, 2},
		{"advise on a missing count file", []string{"advise", "--ua-counts", missing}, 4},
		{"unknown flag", []string{"lint", "--nope", good}, 2},
		{"version", []string{"version"}, 0},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			got, _, _ := runCLI(c.args...)
			if got != c.want {
				t.Errorf("exit code = %d, expected %d", got, c.want)
			}
		})
	}
}

func TestAdviseWritesTheFileOnStdoutAndTheReasoningOnStderr(t *testing.T) {
	// `robotsmith advise … > robots.txt` must produce a clean file: not one byte of prose on stdout.
	counts := writeTemp(t, "ua.txt", "5000 Mozilla/5.0 (compatible; GPTBot/1.4)\n1000 Mozilla/5.0 (compatible; Googlebot/2.1)\n")
	code, stdout, stderr := runCLI("advise", "--ua-counts", counts, "--host", "example.com")
	if code != 0 {
		t.Fatalf("exit code = %d, expected 0. stderr: %s", code, stderr)
	}
	if !strings.HasPrefix(stdout, "# robots.txt generated by robotsmith") {
		t.Errorf("stdout must start with the generated file, got:\n%s", stdout)
	}
	if strings.Contains(stdout, "What I advise") {
		t.Error("the reasoning must not end up in the file")
	}
	if !strings.Contains(stderr, "What I advise") {
		t.Error("the reasoning must be on stderr, where a human reads it")
	}
}

func TestAdviseOutWritesTheFileAndKeepsStdoutEmpty(t *testing.T) {
	counts := writeTemp(t, "ua.txt", "5000 Mozilla/5.0 (compatible; GPTBot/1.4)\n")
	dest := filepath.Join(t.TempDir(), "robots.txt")
	code, stdout, _ := runCLI("advise", "--ua-counts", counts, "--out", dest)
	if code != 0 {
		t.Fatalf("exit code = %d", code)
	}
	if stdout != "" {
		t.Errorf("with --out nothing goes to stdout, got %q", stdout)
	}
	b, err := os.ReadFile(dest)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(b), "User-agent: GPTBot") {
		t.Errorf("the written file must contain the advice:\n%s", b)
	}
}

func TestJSONOutputIsValidAndCarriesItsSchema(t *testing.T) {
	// A pipeline pins the schema: it is the only stable promise, because the prose is free to change.
	counts := writeTemp(t, "ua.txt", "5000 Mozilla/5.0 (compatible; GPTBot/1.4)\n1000 Mozilla/5.0 (compatible; Googlebot/2.1)\n")
	broken := writeTemp(t, "broken.txt", "User-agent: *\n\nDisallow: /admin/\n")

	cases := []struct {
		name   string
		args   []string
		schema string
	}{
		{"check", []string{"check", "--json", serveRobots(t, healthyRobots, 200)}, "robotsmith.check/1"},
		{"lint", []string{"lint", "--json", broken}, "robotsmith.lint/1"},
		{"advise", []string{"advise", "--json", "--ua-counts", counts}, "robotsmith.advise/1"},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			_, stdout, _ := runCLI(c.args...)
			var got map[string]any
			if err := json.Unmarshal([]byte(stdout), &got); err != nil {
				t.Fatalf("stdout is not valid JSON: %v\n%s", err, stdout)
			}
			if got["schema"] != c.schema {
				t.Errorf("schema = %v, expected %s", got["schema"], c.schema)
			}
		})
	}
}

func TestJSONKeepsTheExitCodeAndStdoutJSONOnly(t *testing.T) {
	// --json changes the shape of the answer, never the verdict.
	code, stdout, _ := runCLI("lint", "--json", writeTemp(t, "broken.txt", "User-agent: *\n\nDisallow: /a\n"))
	if code != 1 {
		t.Errorf("exit code = %d, expected 1: --json must not soften the verdict", code)
	}
	var rep struct {
		OK       bool `json:"ok"`
		Errors   int  `json:"errors"`
		Findings []struct {
			Severity string `json:"severity"`
			Line     int    `json:"line"`
		} `json:"findings"`
	}
	if err := json.Unmarshal([]byte(stdout), &rep); err != nil {
		t.Fatal(err)
	}
	if rep.OK || rep.Errors != 1 || len(rep.Findings) != 1 {
		t.Errorf("report = %+v", rep)
	}
	if rep.Findings[0].Severity != "ERROR" || rep.Findings[0].Line != 3 {
		t.Errorf("finding = %+v: severity and line are what a CI annotation needs", rep.Findings[0])
	}
}

func TestAdviseJSONCarriesTheFileAndTheDecisions(t *testing.T) {
	counts := writeTemp(t, "ua.txt", "5000 Mozilla/5.0 (compatible; GPTBot/1.4)\n1000 Mozilla/5.0 (compatible; Googlebot/2.1)\n")
	_, stdout, _ := runCLI("advise", "--json", "--ua-counts", counts)
	var rep struct {
		Total     int64  `json:"total_requests"`
		RobotsTxt string `json:"robots_txt"`
		Decisions []struct {
			Name   string  `json:"name"`
			Family string  `json:"family"`
			Policy string  `json:"policy"`
			Share  float64 `json:"share"`
		} `json:"decisions"`
	}
	if err := json.Unmarshal([]byte(stdout), &rep); err != nil {
		t.Fatal(err)
	}
	if rep.Total != 6000 {
		t.Errorf("total_requests = %d, expected 6000", rep.Total)
	}
	if !strings.Contains(rep.RobotsTxt, "User-agent: GPTBot") {
		t.Error("the advised file must travel inside the JSON: a consumer must not have to run twice")
	}
	byName := map[string]string{}
	for _, d := range rep.Decisions {
		byName[d.Name] = d.Policy
	}
	if byName["GPTBot"] != "block" || byName["Googlebot"] != "allow" {
		t.Errorf("policies = %v", byName)
	}
}
